In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [3]:
df.drop('name',axis=1, inplace=True)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [4]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [5]:
df['horsepower'].fillna(df['horsepower'].median(),inplace=True)
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [7]:
#there is one object and all numerical columns. we need to change the object into numeric

df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [8]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [9]:
df['origin']= df['origin'].map({'usa':1, "japan":2,'europe':3})
df['origin'] = df['origin'].astype(int)
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int32
dtype: object

In [10]:
#separate x and y
X = df.drop('mpg',axis=1)
y = df['mpg']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train , x_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=1)
x_train ,x_test,y_train, y_test

(     cylinders  displacement  horsepower  weight  acceleration  model_year  \
 298          8         350.0       125.0    3900          17.4          79
 13           8         455.0       225.0    3086          10.0          70
 376          4          91.0        68.0    2025          18.2          82
 61           4         122.0        86.0    2226          16.5          72
 346          4          97.0        67.0    2065          17.8          81
 ..         ...           ...         ...     ...           ...         ...
 393          4         140.0        86.0    2790          15.6          82
 255          4         140.0        88.0    2720          15.4          78
 72           8         304.0       150.0    3892          12.5          72
 235          4          97.0        75.0    2265          18.2          77
 37           6         232.0       100.0    3288          15.5          71

      origin
 298       1
 13        1
 376       2
 61        1
 346       2
 ..      ...
 393       1
 255       1
 72        1
 235       2
 37        1

 [318 rows x 7 columns],
      cylinders  displacement  horsepower  weight  acceleration  model_year  \
 174          6         171.0        97.0    2984          14.5          75
 359          4         141.0        80.0    3230          20.4          81
 250          8         318.0       140.0    3735          13.2          78
 274          5         131.0       103.0    2830          15.9          78
 283          6         232.0        90.0    3265          18.2          79
 ..         ...           ...         ...     ...           ...         ...
 146          4          90.0        75.0    2125          14.5          74
 327          5         121.0        67.0    2950          19.9          80
 223          8         318.0       145.0    4140          13.7          77
 159          8         351.0       148.0    4657          13.5          75
 23           4         121.0       113.0    2234          12.5          70

      origin
 174       1
 359       3
 250       1
 274       3
 283       1
 ..      ...
 146       1
 327       3
 223       1
 159       1
 23        3

 [80 rows x 7 columns],
 298    23.0
 13     14.0
 376    37.0
 61     21.0
 346    32.3
        ...
 393    27.0
 255    25.1
 72     15.0
 235    26.0
 37     18.0
 Name: mpg, Length: 318, dtype: float64,
 174    18.0
 359    28.1
 250    19.4
 274    20.3
 283    20.2
        ...
 146    28.0
 327    36.4
 223    15.5
 159    14.0
 23     26.0
 Name: mpg, Length: 80, dtype: float64)

In [13]:
#simple linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
for i, col_name in enumerate(x_train.columns):
    print(f'the coefficient for {col_name} is {model.coef_[i]}')

the coefficient for cylinders is -0.21653780216833265
the coefficient for displacement is 0.019879936208875085
the coefficient for horsepower is -0.012704816241841334
the coefficient for weight is -0.007164698157663282
the coefficient for acceleration is 0.09047636715999348
the coefficient for model_year is 0.846042067259144
the coefficient for origin is 1.4280000651600904

In [16]:
#coeffients arerelativly smaller,means if one independent variable changes slightly 
#there willl be not much difference in prediction
#this is sametime is called smoother model
from sklearn.metrics import r2_score
y_pred = model.predict(x_test)
score = r2_score(y_test, y_pred)
score

0.8563012451456408

In [19]:
# ridge regression
from sklearn.linear_model import Ridge
ridgemodel =Ridge(alpha=0.1)
ridgemodel

Ridge(alpha=0.1)

In [20]:
ridgemodel.fit(x_train,y_train)
for i,col_name in enumerate(x_train.columns):
    print(f'the coefficient for {col_name} is {ridgemodel.coef_[i]}')

the coefficient for cylinders is -0.21615305026026044
the coefficient for displacement is 0.01986221581111451
the coefficient for horsepower is -0.012697324116592825
the coefficient for weight is -0.007164428584491189
the coefficient for acceleration is 0.09045740164184239
the coefficient for model_year is 0.845974707406231
the coefficient for origin is 1.426669100478145

In [22]:
y_pred_ridge = ridgemodel.predict(x_test)
r2_ridge = r2_score(y_test,y_pred_ridge)
r2_ridge

0.8563026607885914

In [23]:
#we don't see much variation in coeff of ridge regression as compared to linear regression

In [24]:
from sklearn.linear_model import Lasso
lasso_model = Lasso(alpha=0.5)
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.5)

In [26]:
for i,col_name in enumerate(x_train.columns):
    print(f'the coefficient for {col_name} is {lasso_model.coef_[i]}')

the coefficient for cylinders is -0.0
the coefficient for displacement is 0.0019772716551741043
the coefficient for horsepower is -0.009291692111718762
the coefficient for weight is -0.006589928565464688
the coefficient for acceleration is 0.0
the coefficient for model_year is 0.7532080062488491
the coefficient for origin is 0.0

In [28]:
#3 featurescoefficient are 0, because lasso helps in feature selection (so we may drop them for better model)
y_pred_lasso = lasso_model.predict(x_test)
r2_lasso = r2_score(y_test,y_pred_lasso)
r2_lasso

0.8457765614927952

In [29]:
#elastic net : use both advantage of ridge and lasso
from sklearn.linear_model import ElasticNet

In [30]:
elasticmodel = ElasticNet(alpha=1,l1_ratio=0.5)

In [31]:
elasticmodel.fit(x_train,y_train)
for i,col_name in enumerate(x_train.columns):
    print(f'the coefficient for {col_name} is {elasticmodel.coef_[i]}')

the coefficient for cylinders is -0.0
the coefficient for displacement is 0.0015384959190967644
the coefficient for horsepower is -0.01064195700207186
the coefficient for weight is -0.006532608594610211
the coefficient for acceleration is 0.0
the coefficient for model_year is 0.7203541472156387
the coefficient for origin is 0.0

In [32]:
y_pred_elastic = elasticmodel.predict(x_test)
r2_elastic = r2_score(y_test,y_pred_elastic)
r2_elastic

0.8477301010951965

In [34]:
from sklearn.linear_model import RidgeCV
ridgecvModel = RidgeCV(cv=5)
ridgecvModel.fit(x_train,y_train)
y_pred_rcv = ridgecvModel.predict(x_test)
r2_rcv = r2_score(y_test,y_pred_rcv)
r2_rcv

0.8563494248817896

In [36]:
ridgecvModel.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [35]:
from sklearn.linear_model import LassoCV
LassoCVModel = LassoCV(cv=5)
LassoCVModel.fit(x_train,y_train)
y_pred_rcv = LassoCVModel.predict(x_test)
r2_Lcv = r2_score(y_test,y_pred_rcv)
r2_Lcv

0.8410032034906063

In [37]:
from sklearn.linear_model import ElasticNetCV
elasticCVModel = ElasticNetCV(cv=5)
elasticCVModel.fit(x_train,y_train)
y_pred_ecv = elasticCVModel.predict(x_test)
r2_ecv = r2_score(y_test,y_pred_rcv)
r2_ecv

0.8410032034906063